apiVersion: apps/v1
kind: Deployment
metadata:
  name: suryadeployauto2
  labels:
    app: autoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autoapp
  template:
    metadata:
      labels:
        app: autoapp
    spec:
      containers:
        - name: mycont5
          image: surya8442/autoassist:v2
          ports:
            - containerPort: 1377
---
apiVersion: v1
kind: Service
metadata:
  name: auto
spec:
  selector:
    app: autoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1377
  type: LoadBalancer
